### ISSUE TITLE
python3-pyqt5.qtwebengine or python3-pyqt5.qtwebchannel missing on some Distributions

### ISSUE THREAD

**Issue by the-solipsist** [jabbercat/jabbercat#10]
Ubuntu 16.04 has no install candidates for [python3-pyqt5.qtwebengine](https://packages.ubuntu.com/zesty/python3-pyqt5.qtwebengine) or for [python3-pyqt5.qtwebchannel](https://packages.ubuntu.com/zesty/python3-pyqt5.qtwebchannel).

I'm running Ubuntu 16.04, and had to install `qt5-default` to avoid the rcc-related issues.  Then I did `make` again.  Here's the output.
```
(env) sol@spica:~/code/.jctest/jabbercat$ make
./utils/buildui.py -5 data/tasks_status_widget.ui jabbercat/ui/tasks_status_widget.py
./utils/buildui.py -5 data/dlg_presence_modes.ui jabbercat/ui/dlg_presence_modes.py
./utils/buildui.py -5 data/dlg_input_jid.ui jabbercat/ui/dlg_input_jid.py
./utils/buildui.py -5 data/roster_tags.ui jabbercat/ui/roster_tags.py
./utils/buildui.py -5 data/dlg_join_muc.ui jabbercat/ui/dlg_join_muc.py
./utils/buildui.py -5 data/dlg_password_prompt.ui jabbercat/ui/dlg_password_prompt.py
./utils/buildui.py -5 data/p2p_conversation.ui jabbercat/ui/p2p_conversation.py
./utils/buildui.py -5 data/dlg_account_manager.ui jabbercat/ui/dlg_account_manager.py
./utils/buildui.py -5 data/roster_msg_box_stack.ui jabbercat/ui/roster_msg_box_stack.py
./utils/buildui.py -5 data/dlg_custom_presence_states.ui jabbercat/ui/dlg_custom_presence_states.py
./utils/buildui.py -5 data/dlg_data_form.ui jabbercat/ui/dlg_data_form.py
./utils/buildui.py -5 data/dlg_edit_custom_presence.ui jabbercat/ui/dlg_edit_custom_presence.py
./utils/buildui.py -5 data/roster_msg_box.ui jabbercat/ui/roster_msg_box.py
./utils/buildui.py -5 data/roster_tags_box.ui jabbercat/ui/roster_tags_box.py
./utils/buildui.py -5 data/dlg_account_editor.ui jabbercat/ui/dlg_account_editor.py
./utils/buildui.py -5 data/dlg_check_certificate.ui jabbercat/ui/dlg_check_certificate.py
./utils/buildui.py -5 data/account_manager.ui jabbercat/ui/account_manager.py
./utils/buildui.py -5 data/dlg_add_contact.ui jabbercat/ui/dlg_add_contact.py
./utils/buildui.py -5 data/tag_bubble.ui jabbercat/ui/tag_bubble.py
./utils/buildui.py -5 data/dlg_add_account_page_credentials.ui jabbercat/ui/dlg_add_account_page_credentials.py
./utils/buildui.py -5 data/dlg_add_account.ui jabbercat/ui/dlg_add_account.py
./utils/buildui.py -5 data/tasks_popup_frame.ui jabbercat/ui/tasks_popup_frame.py
./utils/buildui.py -5 data/tags_input.ui jabbercat/ui/tags_input.py
./utils/buildui.py -5 data/dlg_add_account_page_connecting.ui jabbercat/ui/dlg_add_account_page_connecting.py
./utils/buildui.py -5 data/main.ui jabbercat/ui/main.py
cd data; rcc --binary -o ../resources.rcc resources.qrc
(env) sol@spica:~/code/.jctest/jabbercat$ python3 -m jabbercat 
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/sol/code/.jctest/jabbercat/jabbercat/__main__.py", line 15, in <module>
    import jabbercat.main
  File "/home/sol/code/.jctest/jabbercat/jabbercat/main.py", line 18, in <module>
    from . import (
  File "/home/sol/code/.jctest/jabbercat/jabbercat/conversation.py", line 84, in <module>
    class MessageViewPage(Qt.QWebEnginePage):
AttributeError: module 'jabbercat.Qt' has no attribute 'QWebEnginePage'
```

**Comment by horazont** [comment]
Confirmed to be affected:

* Ubuntu 16.04
* Debian 8

Those are too out-of-date to run JabberCat. Remember that JabberCat is still alpha software, which is why we don’t care *too* much about that **for now**.
