### ISSUE TITLE
Cache is corrupt after unclean shutdown

### ISSUE THREAD

**Issue by horazont** [jabbercat/jabbercat#11]
Manifests in traceback like:
```
DEBUG:jclib.storage.frontends.XMLFrontend:opening storage for type <StorageType.CACHE: 'cache'> at level AccountLevel(account=JID([redacted])), looking for XSO class <class 'jclib.xso.RosterContact'>
ERROR:aioxmpp.callbacks:listener attached to signal raised
Traceback (most recent call last):
  File "/home/<redacted>/build/jclib/jclib/storage/frontends.py", line 786, in _open
    return self.__open_storages[type_, cache_key]
KeyError: (<StorageType.CACHE: 'cache'>, (<StorageLevel.ACCOUNT: 'account'>,))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/xml/sax/expatreader.py", line 210, in feed
    self._parser.Parse(data, isFinal)
xml.parsers.expat.ExpatError: no element found: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/<redacted>/build/aioxmpp/aioxmpp/callbacks.py", line 536, in fire
    keep = wrapper(args, kwargs)
  File "/home/<redacted>/build/aioxmpp/aioxmpp/callbacks.py", line 470, in _strong_wrapper
    return not f(*args, **kwargs)
  File "/home/<redacted>/build/jclib/jclib/roster.py", line 738, in _prepare_client
    instance.load()
  File "/home/<redacted>/build/jclib/jclib/roster.py", line 576, in load
    jclib.xso.RosterContact,
  File "/home/<redacted>/build/jclib/jclib/storage/frontends.py", line 853, in get_all
    data = self._open(type_, level)
  File "/home/<redacted>/build/jclib/jclib/storage/frontends.py", line 788, in _open
    data = self._load(type_, level)
  File "/home/<redacted>/build/jclib/jclib/storage/frontends.py", line 758, in _load
    storage_cls,
  File "/home/<redacted>/build/aioxmpp/aioxmpp/xml.py", line 1101, in read_single_xso
    read_xso(src, {type_: cb})
  File "/home/<redacted>/build/aioxmpp/aioxmpp/xml.py", line 1086, in read_xso
    parser.parse(src)
  File "/usr/lib/python3.5/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python3.5/xml/sax/xmlreader.py", line 127, in parse
    self.close()
  File "/usr/lib/python3.5/xml/sax/expatreader.py", line 222, in close
    self.feed("", isFinal = 1)
  File "/usr/lib/python3.5/xml/sax/expatreader.py", line 214, in feed
    self._err_handler.fatalError(exc)
  File "/usr/lib/python3.5/xml/sax/handler.py", line 38, in fatalError
    raise exception
xml.sax._exceptions.SAXParseException: /home/<redacted>/.cache/jabbercat.org/global/dns%3Ajabbercat.org/xml-storage/account.xml:1:0: no element found
```

And also empty window (no roster). 

* Reproducer: truncate ``account.xml`` in cache.
* Workaround: delete ``~/.cache/jabbercat.org`` recursively (everything in ``~/.cache/jabbercat.org`` is disposable an can safely be deleted)

1. The cache should never become corrupt in the first place.
2. A corrupt cache should not hinder operations. We should catch any parsing errors and discard the cache if they occur (as the cache is disposable).

Thanks to @mdosch for discovering this.

**Comment by horazont** [comment]
Fixed by jclib commits [21c68d3](https://github.com/jabbercat/jclib/commit/21c68d35006eac47f223423d92a9832083eccfc8) (improves protection against corruption happening in the first place) and [ce207e1](https://github.com/jabbercat/jclib/commit/ce207e1161c71e0a56786154f32e2124b7659615) (handles corruption gracefully).

To test that recovery works, you can (1) stop jabbercat, (2) truncate the ``~/.cache/jabbercat.org/…/account.xml`` file and (3) start jabbercat. The roster should now be visible instead of empty.

Testing that prevention works better now would require an actual hard crash ;-).
